### ISSUE TITLE
Be able to have a cshtml that contain main.js and its chunks.

### ISSUE THREAD

**Issue by jbailly1** [jouni-kantola/razor-partial-views-webpack-plugin#49] opened 2021-01-10 02:07 UTC
In my company we use a old asp.net style webapp. But have new page in react.
We want to improved the bundles size by split chunks.

I found your plugin very interesting.
But I found that it's not possible to create a cshtml will contains the entry and its chunks in orders.

Thanks

**Comment by jouni-kantola** [comment] 2021-01-11 19:22
@jbailly1 Create one Razor partial per entry in webpack. This enables you to control the order the scripts should be loaded. These you do not load async.

The code splitted chunks you can leave to webpack's async loading. These you don't need razor partials for.

**Comment by jouni-kantola** [comment] 2021-01-11 19:39
As guidance, what you should look at is the following from the webpack docs:
https://webpack.js.org/guides/code-splitting/#dynamic-imports

From that example, you'd want to match the `index` chunk with `razor-partial-views-webpack-plugin` the following way:
```js
new RazorPartialViewsWebpackPlugin({
  rules: [
    {
      name: ["index"],
    },
  ],
})
```

**Comment by jbailly1** [comment] 2021-01-12 01:28
Thanks for our answer.
We don't use yet the dynamic loader except for one module.
But we found a solution with htmlWebpackPlugin that take a cshtml template, loop in the chunks file
and insert a script with the url.
And generate a cshtml that contains the right script url.
But if we will use the dynamic loading, maybe we hope to use your plugin.

**Comment by jbailly1** [comment] 2021-01-12 01:28
You can close the issue I think

**Comment by jouni-kantola** [comment] 2021-01-12 01:34
Glad you found a solution! 👍 

I may have misunderstood the problem you were facing as well. If you have a possibility to provide a snippet how you solve your asset referencing with `html-webpack-plugin` I may be able to guide you.

I'll close the issue, but please continue discussing here if you want to proceed looking at `razor-partial-views-webpack-plugin`.

**Closed by jouni-kantola** 2021-01-12 01:34 UTC
Labels: question

**Comment by jbailly1** [comment] 2021-01-12 02:35
I use this article https://cecilphillip.com/setting-up-webpack-in-asp-net-core-pt-2/ 
To simplify he insert 
`
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
    <script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
    <% } %>
`
into a cshtml template and use that template to generate a cshtml with the chunks in the order

Webpack config
`
new HtmlWebpackPlugin({
          inject: false,
          template: 'Views/Shared/_LayoutTemplate.cshtml',
          filename: '../../Views/Shared/_Layout.cshtml'
      }),
`

So my initial question was is it possible to do the same thing with your plugins.

**Comment by jouni-kantola** [comment] 2021-01-12 02:59
Thank you for pinging back. I appreciate it! `html-webpack-plugin` is a great plugin. You'll not go wrong with that choice. The only downside I see is that you'll render your whole Razor layout, which can be a bit cumbersome at times in ASP.NET land.

I don't know how many chunks you are referencing in ASP.NET, but I personally would recommend handing as much work over to webpack as possible. 

With that said, `razor-partial-webpack-plugin` references one asset per partial view. That is by design. The reason why, is because it then comes down to deciding server side when to render the asset, either inline (often done with webpack's runtime) or linked scripts/styles/etc URL references. Where you think they are suitable to load, in head or bottom of body, etc.

A guide that is a good starter for choosing which assets to render is: https://webpack.js.org/guides/caching/
webpack generated assets in that guide can then be targeted with `razor-partial-webpack-plugin` in multiple ways, but only one view per asset will be created.

I hope that helps with the ideas behind the plugin. Good luck!
